# Uncomment the next line to define a global platform for your project
 platform :ios, '9.0'

target 'Sampler_App' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Sampler_App
     pod 'CocoaAsyncSocket'

  target 'Sampler_AppTests' do
    inherit! :search_paths
    # Pods for testing
     pod 'CocoaAsyncSocket'

  end

  target 'Sampler_AppUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
